<template>
  <div id="head">
  	<div class="contain ">
  		<div class="screen">
  			<div class="title">
  				  {{ message }}  
  			</div>
  		</div>
    	<p class="subj basetext">{{subj}}</p> 
			<div  class="cont ">
				<div class="plashka"><p>{{cont}}</p></div>
			</div>
    </div>
  </div>
</template>

<script>
import ScrambleText from 'scramble-text'; 
export default {
  data: function () {
    return {
    	subj: 'Разработка веб-приложений, сайтов на Ruby on Rails + Vue.js',
      message: "Pixeltech",
      cont: "admin@pixeltech.ru"
    }
  },
  mounted() {
  var cont = document.querySelector(".cont");
  var scrambleText = new ScrambleText( cont,
		{
			timeOffset : 100,
			// chars: [
			// 	'安','以','宇','衣','於',
			// 	'加','幾','久','計','己',
			// 	'左','之','寸','世','曽',
			// 	'太','知','川','天','止',
			// 	'奈','仁','奴','称','乃',
			// 	'波','比','不','部','保',
			// 	'末','美','武','女','毛',
			// 	'也','為','由','恵','与',
			// 	'良','利','留','礼','呂',
			// 	'和','遠','无'
			// ],
			callback: function () { console.log( 'ended' ); }
		} ).play();
		this.tween();
    setTimeout(function(){
       
      // self.cropText();
       scrambleText.start();  

    },1000 );

	

		 
  },
  methods: {
  	tween() {
      var selectedWork = new TimelineMax() ;
      selectedWork
       
      .staggerFromTo('.title', 0.2, {

        // autoAlpha:0,
        // scaleX: 0.8,
       	scaleY: 0, 
        // xPercent: -350,
        
      }, {
       transformOrigin: '50% 50%',
      	// scaleX: 1,
      	scaleY: 1, 
        // autoAlpha:1,
        // xPercent: 0,
        ease:Expo.easeIn}, 0.5, "+=1.0")
      .staggerFromTo('.subj', 1, {
         autoAlpha:0,
         yPercent: 100,
      }, {
         autoAlpha:1,
         yPercent: 0,
        ease:Power4.easeOut,}, 0, "-=12")
      .staggerFromTo('.cont', 5, {
      	 
         xPercent: -250,
      }, {
         
        xPercent: 0,
        ease:Circ.easeIn}, 0, "-=16.4");
  	}
  }
}
</script>
<style scoped>
@import "_variables";
@import "_extends";
#head { 
	align-items: center;
	/*lost-utility: edit;*/
	lost-center: 24em;
	height: 100vh;
	display: flex;
	@media (--only-xsmall-screen) {
  	 h2 {
  	 	adjust-font-size: fs medium;
  	 }
  }
  @media (--only-small-screen) {
 
  }
	@media (--only-medium-screen) {
 
	  h1 {
			margin-top: spacing(0);
		}
  }
  @media (--only-1600more-screen) {
 
  	lost-center: 600px;
	  h1 {
			margin-top: spacing(0);
		}
  }
}
.contain { 
	padding-left: 0.6em; 
	padding-right: 0.6em; 
	overflow: hidden;
	position: relative;
}
.screen {
	border-top-left-radius: 0.3em;
	border-top-right-radius: 0.3em;
	overflow: hidden;
	@extend %screenbg;
	padding: 0em 1em 0.1em 0em;
	display: flex;
	justify-content: center;
}
.title {
	adjust-font-size: 2em;
	line-height: 1.4em;
	padding: 0.0em 0.4em;
	vertical-align: top;
	margin-bottom: spacing(0); 
	color: $color-5;
}
.subj {
	margin-bottom: spacing(0);
  color: $titleColor;
	padding: 0.7em 0.5em 0.7em 0.7em;
}

.cont {
	display: flex;
 border-bottom-right-radius: 2.5em;
 border-bottom-left-radius: 2.5em;
	@extend %screenbg;
	padding: 0.2em 0.5em 0 0em;
	justify-content: center;
	p {
		margin-bottom: spacing(0);
		color: $color-5;
		padding: 0em 0.2em 0.3em 0.5em;
	}
	min-width: 10em;
}
.plashka {
	text-align: left;
}


.flicker-in-1 {
	-webkit-animation: flicker-in-1 2s linear both;
	        animation: flicker-in-1 2s linear both;
} 
/* ----------------------------------------------
 * Generated by Animista on 2018-7-24 14:32:43
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * @animation flicker-in-1
 * ----------------------------------------
 */
@-webkit-keyframes flicker-in-1 {
  0% {
    opacity: 0;
  }
  10% {
    opacity: 0;
  }
  10.1% {
    opacity: 1;
  }
  10.2% {
    opacity: 0;
  }
  20% {
    opacity: 0;
  }
  20.1% {
    opacity: 1;
  }
  20.6% {
    opacity: 0;
  }
  30% {
    opacity: 0;
  }
  30.1% {
    opacity: 1;
  }
  30.5% {
    opacity: 1;
  }
  30.6% {
    opacity: 0;
  }
  45% {
    opacity: 0;
  }
  45.1% {
    opacity: 1;
  }
  50% {
    opacity: 1;
  }
  55% {
    opacity: 1;
  }
  55.1% {
    opacity: 0;
  }
  57% {
    opacity: 0;
  }
  57.1% {
    opacity: 1;
  }
  60% {
    opacity: 1;
  }
  60.1% {
    opacity: 0;
  }
  65% {
    opacity: 0;
  }
  65.1% {
    opacity: 1;
  }
  75% {
    opacity: 1;
  }
  75.1% {
    opacity: 0;
  }
  77% {
    opacity: 0;
  }
  77.1% {
    opacity: 1;
  }
  85% {
    opacity: 1;
  }
  85.1% {
    opacity: 0;
  }
  86% {
    opacity: 0;
  }
  86.1% {
    opacity: 1;
  }
  100% {
    opacity: 1;
  }
}
@keyframes flicker-in-1 {
  0% {
    opacity: 0;
  }
  10% {
    opacity: 0;
  }
  10.1% {
    opacity: 1;
  }
  10.2% {
    opacity: 0;
  }
  20% {
    opacity: 0;
  }
  20.1% {
    opacity: 1;
  }
  20.6% {
    opacity: 0;
  }
  30% {
    opacity: 0;
  }
  30.1% {
    opacity: 1;
  }
  30.5% {
    opacity: 1;
  }
  30.6% {
    opacity: 0;
  }
  45% {
    opacity: 0;
  }
  45.1% {
    opacity: 1;
  }
  50% {
    opacity: 1;
  }
  55% {
    opacity: 1;
  }
  55.1% {
    opacity: 0;
  }
  57% {
    opacity: 0;
  }
  57.1% {
    opacity: 1;
  }
  60% {
    opacity: 1;
  }
  60.1% {
    opacity: 0;
  }
  65% {
    opacity: 0;
  }
  65.1% {
    opacity: 1;
  }
  75% {
    opacity: 1;
  }
  75.1% {
    opacity: 0;
  }
  77% {
    opacity: 0;
  }
  77.1% {
    opacity: 1;
  }
  85% {
    opacity: 1;
  }
  85.1% {
    opacity: 0;
  }
  86% {
    opacity: 0;
  }
  86.1% {
    opacity: 1;
  }
  100% {
    opacity: 1;
  }
}

</style>
